{% set version = "5.4.8" %}

package:
  name: lua
  version: {{ version }}

source:
  fn: lua-{{ version }}.tar.gz
  url: https://www.lua.org/ftp/lua-{{ version }}.tar.gz
  md5: 81cf5265b8634967d8a7480d238168ce

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  # host:
  #   - readline
  #   - ncurses
  # run:
  #   - readline
  #   - ncurses

test:
  commands:
    - test -f $PREFIX/bin/lua
    - test -f $PREFIX/bin/luac
    - test -f $PREFIX/lib/liblua.a
    - test -f $PREFIX/include/lua.h
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT

extra:
  recipe-maintainers:
    - alexbw
