{% set version = "5.4.8" %}

package:
  name: lua
  version: {{ version }}

source:
  fn: lua-{{ version }}.tar.gz
  url: https://www.lua.org/ftp/lua-{{ version }}.tar.gz
  sha256: 4f18ddae154e793e46eeab727c59ef1c0c0c2b744e7b94219710d76f530629ae
  patches:
    - 0001-default-compiler.patch

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - patch
    - make

test:
  commands:
    - test -f $PREFIX/bin/lua
    - test -f $PREFIX/bin/luac
    - test -f $PREFIX/lib/liblua.a
    - test -f $PREFIX/include/lua.h
    - lua -v
    - lua -e "print(\"Lua path:\" .. package.path)"
    - lua -e "print(\"Lua cpath:\" .. package.cpath)"

about:
  home: https://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_family: MIT
  license_url: https://www.lua.org/license.html
  doc_url: https://www.lua.org/docs.html
  dev_url: https://www.lua.org/source/
  description: |
    Lua is a powerful, efficient, lightweight, embeddable scripting language.
    It supports procedural programming, object-oriented programming, functional 
    programming, data-driven programming, and data description.

extra:
  recipe-maintainers:
    - alexbw
