travis:
  secure:
    BINSTAR_TOKEN: fDPQhZxWppDl4WIFD1FqharInputlCdnqSV0oIHyjmePJiBYeUotxfmfSLT3xNw111cw5KMiFtyX+Dj6TzmkpqDSuwPXyCLmx+0OXQ1xLeW1XIBhoiAJc9wA0pWIfVH9PoPNuSGDK1Y+IEwJYbp6ACGfeKb9lFY85YyO2bqrZ+xllB/VzAp2sfQXw0xiOJ+SvGwg5ptev1DxMMH4LlDFvmlR2EgqaALlb3xLf7H+wygYK5uK73j8JidkhVdSFSVjEVhs7IhCZtYcPOv2Ch9kwOPJrbr5credtFmwSkQYRO6S+IPcVlXr34lJ31g4p5CMxW95cOAhrOVSTj2W1BNICDMwBCHeMhELZH/aEdGgoK/z8Jn2djYMOUURnPzehetyPLhhFLRB9oSlOsaEO5i2jCYGUAK1ogCfqfniom0qW6oodNJN2INpRQjJZpP+Ykoc57s1UOo6uG2xiFKEGWoLbGtjn7d8T/HkX7UWrmZDHqgnOOx+n0Fu8xziHupNOMVp+rAClRNBqexsHhuZyVqyIz24PTMr/3l85cgm/bZ+7yX8RLzyIERLrkP4UUBW/ixjt9a7TB4MD7lJc3Lf7Lq2EX3AcTstRcTwBgZMg+LExoNQ49Vo24Dt0muu1tgztgPmgIGHYZbzhhGLxeu3+W590YX8/1EAFfohb9vX/DhOQNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
